### ISSUE TITLE
[Bug] Same key has already been added

### ISSUE THREAD

**Issue by jaymarvels** [mkaring/ConfuserEx#34] opened 2019-03-22 11:12 UTC
Trying to run confuser against my project and some of the class libraries that it builds and get the following error:

 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
 [WARN] [EntityFramework.dll] SN Key is not provided for a signed module, the output may not be working.
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[ERROR] Unknown error occurred.
Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Confuser.Renamer.VTable.Implements(VTableConstruction vTbl, Dictionary`2 virtualMethods, VTable ifaceVTbl, TypeSig iface)
   at Confuser.Renamer.VTable.ConstructVTable(TypeDef typeDef, VTableStorage storage)
   at Confuser.Renamer.VTableStorage.GetOrConstruct(TypeDef type)
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
Failed at 11:10, 0:04 elapsed.

**Comment by mkaring** [comment] 2019-03-22 12:09
What version of ConfuserEx are you using?
What protections are you using (you can also share the `*.crproj` file you are using, make sure to remove any passwords for private keys if there are any)
Do you have a minimal working example that produces the error?

**Comment by jaymarvels** [comment] 2019-03-22 12:47
@mkaring  

Latest release (1.1.0). 
Normal preset out of the box
I've worked out its just one single project library its failing on with the above error. It doesn't contain any passwords for private keys.

Not sure how I can create a minimal working example to be fair. But the project in question is only full of interface abstractions, methods along with some automapper mappings

**Comment by jaymarvels** [comment] 2019-03-22 15:55
@mkaring  I am going to guess its something around lines 272 and 276 of VTable.cs?

**Comment by mkaring** [comment] 2019-03-23 17:00
@jaymarvels I tried to find the issue without anything to go on but the stacktrace. The problem points to some issue with the interfaces. It seems it's trying to add two methods with identical signatures to the internal structures, but I am not sure how such a thing could happen, because that would mean that a single interface contains the same method twice.

Could you try to disable the "normal" preset and only enable the renaming? To see if the renamer causes the issue on it's own or if the issue is just a side effect of an error in another protection.

The problem is related to interfaces. Are there any strange interface constructions in the assembly that come to mind? Any indication is helpful. I tried different structures of inheriting the interfaces different way, but there was no way to get it to populate a slot twice.

Is there any chance that you can share the affected assembly so I can research the issue using it? You can send it to me at karing.martin@gmail.com if that is possible. I'll treat it as confidential obviously.

**Comment by jaymarvels** [comment] 2019-03-24 12:18
@mkaring  I will give it a try. There is some polymorphism/overloading going on in some of the interfaces too, but this is just normal OOP practices.

I'll let you know the results of renaming only

**Comment by jaymarvels** [comment] 2019-03-24 12:21
@mkaring  Renaming fails too:

` [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[ERROR] Unknown error occurred.
Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Confuser.Renamer.VTable.Implements(VTableConstruction vTbl, Dictionary`2 virtualMethods, VTable ifaceVTbl, TypeSig iface)
   at Confuser.Renamer.VTable.ConstructVTable(TypeDef typeDef, VTableStorage storage)
   at Confuser.Renamer.VTableStorage.GetOrConstruct(TypeDef type)
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
Failed at 12:20, 0:01 elapsed.`

**Comment by jaymarvels** [comment] 2019-03-24 12:56
@mkaring 

Think I've found the interface in question:

`    public interface IModelRepository<T>
    {
        FileReadResults<T> Create(string path);

        SaveFileReadResults<T> Create(BinaryReader reader);

        void Write(BinaryWriter binaryWriter, long objectIndex, List<T> objectList, List<T> objectAltList);

        void Write(string path, List<Club> objectList, List<Club> objectAltList, long objectIndex);

        void Write(string path, List<T> objectList, List<T> objectAltList, long objectIndex);

    }`

Looks like as I have a mix of generic and strongly typed with the same signature it doesn't like it.

**Comment by mkaring** [comment] 2019-03-24 17:51
Is there an class implementing this interface or another interface extending this interface with `Club` as generic typefor `T`?

**Comment by jaymarvels** [comment] 2019-03-24 20:43
@mkaring  I removed 

`void Write(string path, List<Club> objectList, List<Club> objectAltList, long objectIndex);`

as these 2 signatures are the same:

from the interface and obviously all the implementations, and this all seems to have fixed it and its working, I am thinking this is some weird R# thing when I did a Pull Up to the interface.

`    void Write(string path, List<Club> objectList, List<Club> objectAltList, long objectIndex);

    void Write(string path, List<T> objectList, List<T> objectAltList, long objectIndex);`

Unless you think this is a legit bug and you want to fix it?

Thanks for your help

**Comment by mkaring** [comment] 2019-03-24 21:58
It is a legit bug. It is possible that a single method overrides multiple interface method signatures. That is a valid case and it will be fixed in the next release. It would be great if you could keep an affected version of your assembly around a couple of days, so you can test the new version of ConfuserEx and verify that the issue is fixed.

**Comment by mkaring** [comment] 2019-03-24 22:40
@jaymarvels Find the new build here: https://ci.appveyor.com/project/mkaring/confuserex/builds/23321904/artifacts

Could you please try if that version is able to properly handle your assembly?

**Comment by jaymarvels** [comment] 2019-03-25 10:37
@mkaring  I tested against my pre modified assembly and now its functioning correctly.

Thanks

**Comment by mkaring** [comment] 2019-03-25 11:56
Very good. Thank you. The patch will be included in the next release.

**Closed by mkaring** 2019-03-25 11:56 UTC
Labels: bug

**Comment by Gwindalmir** [comment] 2019-08-14 21:41
Was this fix included in the 2.0.0 build on nuget?
I used this package, but get the same error: [https://ci.appveyor.com/api/buildjobs/hugwqwjv3avids2r/artifacts/Confuser.MSBuild.Tasks%2Fbin%2FRelease%2FConfuser.MSBuild.2.0.0-alpha.232.nupkg](https://ci.appveyor.com/api/buildjobs/hugwqwjv3avids2r/artifacts/Confuser.MSBuild.Tasks%2Fbin%2FRelease%2FConfuser.MSBuild.2.0.0-alpha.232.nupkg)

I have the same error, reproducible with the following code:
`    public class Class1
    {
        internal void Method()
        {
        }

        [Obfuscation(Exclude = false, Feature = "preset(maximum);-anti tamper;+rename(mode=decodable)")]
        internal void Method(bool argument)
        {
        }
    }
`
