### ISSUE TITLE
CONSTANTS protection produces null/empty string in sattelite assembly

### ISSUE THREAD

**Issue by FlavijeC** [mkaring/ConfuserEx#193] opened 2020-08-14 14:50 UTC
[!Confuserex 2 [Bug Submit].zip](https://github.com/mkaring/ConfuserEx/files/5075194/Confuserex.2.Bug.Submit.zip)

Situation:
1. There are main exe and sattelite dll. 
2. Constants protection is enabled

Call sattelite dll function, called from main exe returns null/empty string insted of inline string constant

function in main exe that calls dll fn
```
        private void button1_Click(object sender, EventArgs e)
        {
            string sRowFilter = "";
            ClassLibrary1.Class1.AppendRowFlter(ref sRowFilter, "fieldName", "operatorString", "value");
        }

```

and overloaded fn in dll that  produces bug
```
    public static class Class1
    {
        public static void AppendRowFlter(ref string rowFilter, string fieldName, string operatorString, object value)
        {
            AppendRowFlter(ref rowFilter, fieldName, operatorString, value, "AND");
            //MessageBox.Show("hello"); //if this line is enabled, no error is produced
        }

        public static void AppendRowFlter(ref string rowFilter, string fieldName, string operatorString, object value, string condition)
        {
            MessageBox.Show("condition: " + Convert.ToString(condition));
        }
    }
```

NOTE: if another line is added, bug dissapers:
`
 //MessageBox.Show("hello"); //if this line is enabled, no error is produced
`

Minimal example in c# (VS2015) project is attached.

**Comment by mkaring** [comment] 2020-08-16 12:08
I'm able to reproduce the issue. Thank you for the example.

**Comment by mkaring** [comment] 2020-08-16 12:56
I found the reason for the issue. The problem is caused by the method inlining done by the JIT compiler. The constants protection has an internal check that verifies that it's only called by the assembly that contains the protected constant.
In your case the `AppendRowFlter` method is inlined into the `button1_Click` method. That means that the call to the method that decodes the constant, is done by the `WindowsFormsApplication1` assembly, where the decoder function expects the caller to be in the `ClassLibrary1` assembly.

As a work around I suggest either to disable the constants protection for very short methods or to add the `[MethodImpl(MethodImplOptions.NoInlining)]` attribute to the method that is affected.

The issue will be fixed in the next version of ConfuserEx.

**Comment by FlavijeC** [comment] 2020-08-16 13:35
> I found the reason for the issue. The problem is caused by the method inlining done by the JIT compiler. The constants protection has an internal check that verifies that it's only called by the assembly that contains the protected constant.
> In your case the `AppendRowFlter` method is inlined into the `button1_Click` method. That means that the call to the method that decodes the constant, is done by the `WindowsFormsApplication1` assembly, where the decoder function expects the caller to be in the `ClassLibrary1` assembly.
> 
> As a work around I suggest either to disable the constants protection for very short methods or to add the `[MethodImpl(MethodImplOptions.NoInlining)]` attribute to the method that is affected.
> 
> The issue will be fixed in the next version of ConfuserEx.
> 
> EDIT:
> The reason why adding the `MessageBox.Show` line helps to prevent this issue, is that the method exceeds the length for the automatic inlining in that case. This means the method is not inlined anymore and the issue is gone.

**Well done maestro @mkaring ** 👍  🥇

**Comment by mkaring** [comment] 2020-08-16 14:47
@FlavijeC: I got a build that should fix the issue. You can download the new build [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/34683358/artifacts). Please give it a go and see if that resolves the issue for your project.

**Comment by FlavijeC** [comment] 2020-08-16 15:38
> @FlavijeC: I got a build that should fix the issue. You can download the new build [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/34683358/artifacts). Please give it a go and see if that resolves the issue for your project.

Works like a charm. 👍 
Thank you @mkaring

**Closed** 2020-08-16 16:01 UTC
Labels: bug, good first issue
