### ISSUE TITLE
MS Build Task 1.3.1 and project Targeted netcoreapp2.1

### ISSUE THREAD

**Issue by magneticcore** [mkaring/ConfuserEx#134] opened 2020-04-22 14:21 UTC
MS Build ConfuserEx2 Task 1.3.1
Visual Studio 2017
Library project Targeted netcoreapp2.1

Following the instructions given in  #59, I tried to build a library project targeted netcoreapp2.1 and the ConfuserEx2 MS Build task gave a lot of errors, the first one being:
> Could not resolve type: System.MarshalByRefObject (System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)

**Comment by mkaring** [comment] 2020-04-23 06:52
There are a couple of issues that will be resolved with the upcoming 1.4 release. This should also resolve the issue you're facing. Have a look at [this repository][0]. You need to set up the [`NuGet.config`][1] file and [the reference to the msbuild package][2] to use the preview version, once that is done it should work.

Give it a try.

[0]: https://github.com/mkaring/TestApp
[1]: https://github.com/mkaring/TestApp/blob/master/NuGet.config#L4
[2]: https://github.com/mkaring/TestApp/blob/master/TestApp.Lib/TestApp.Lib.csproj#L18

**Comment by wjk** [comment] 2020-04-24 03:25
I’m afraid it still doesn’t work for me. My error is complaining about `System.Reflection.Assembly (System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b 03f5f7f11d50a3a)`. I’m using that exact version of the project. I’m targeting netcoreapp3.1, and using WPF. Thanks!

**Comment by mkaring** [comment] 2020-05-02 09:05
I tried to reproduce the error by adding some more tests to the repository mentioned above, but I was unable to produce any error. It all seems to work fine.

**Comment by mkaring** [comment] 2020-06-28 13:36
Closing the issue because it would not be reproduced.

**Closed by mkaring** 2020-06-28 13:36 UTC
