### ISSUE TITLE
Skip rename  satellite assembly. With sample Project

### ISSUE THREAD

**Issue by BBUBBA** [mkaring/ConfuserEx#389] opened 2021-07-29 04:50 UTC
- ConfuserEx Version: 1.5.0
- Target Framework: 4.0
- Operating System: win10 x64

Steps to Reproduce:

1.  https://github.com/mkaring/ConfuserEx/issues/388  <-- case 2

Sample File download
[TEST.zip](https://github.com/mkaring/ConfuserEx/files/6897952/TEST.zip)

![image](https://user-images.githubusercontent.com/17864839/127433483-2712d730-0b5f-4141-a7bd-fccf064d60bc.png)

Test Project have 2 Views 
but es Language file rename Good.
ko-kr Language file rename NG.

Thank you ^^

have a nice day !!!!!!!

**Comment by mkaring** [comment] 2021-07-30 21:25
The reason for the strange issues is that the Korean language code is that for some reason it's once written `ko-KR` and once `ko-kr`. The assembly is marked with `ko-kr`. The issue is that ConfuserEx compares the language codes case sensitive and that is an error. It will be fixed soon.

**Comment by mkaring** [comment] 2021-07-30 22:24
You can find a build fixing this issue [here on the buildserver](https://ci.appveyor.com/project/mkaring/confuserex/builds/40199336/artifacts). Give it a try and let me know if it works for your.

**Comment by BBUBBA** [comment] 2021-07-31 06:10
Good Morning ^^

i Check now !!

![image](https://user-images.githubusercontent.com/17864839/127730575-cc8c6f34-c07b-47b2-bfbc-277c69a05010.png)

https://github.com/mkaring/ConfuserEx/issues/388

Case 2. Fix it !! Good Work!!


I hope... Confuserex can merge satellite assembly With out... Compress T_T.. ( about case 1 )


thank you!! your support !!
( i will send to you coffee ~! lol !!!! )

**Comment by mkaring** [comment] 2021-07-31 08:57
Alright. One down. Thank you for the coffee 😄

**Closed** 2021-07-31 08:57 UTC
Labels: bug
