### ISSUE TITLE
failed to obfuscate a winform project using DataGridView

### ISSUE THREAD

**Issue by ismlsmile** [mkaring/ConfuserEx#54] opened 2019-06-01 08:16 UTC
Debug Info:
```TXT
 [INFO] Confuser.Core 1.2.0+4110faee9d Copyright © 2014 Ki, 2018 Martin Karing
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'TestWinForm.exe'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
[DEBUG] WinForms found, enabling compatibility.
 [WARN] Failed to extract binding property name in 'System.Void TestWinForm.Form1::InitializeComponent()'.
 [INFO] Processing module 'TestWinForm.exe'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'TestWinForm.exe'...
[DEBUG] Encrypting resources...
 [INFO] Finalizing...
[DEBUG] Saving to 'D:\Code\TestWinForm\TestWinForm\bin\TestWinForm.exe'...
[DEBUG] Executing 'Export symbol map' phase...
 [INFO] Done.
Finished at 16:08, 0:02 elapsed.
```

There is a warning when obfuscating. And the target file is created, but when click it, no windows is shown.

The function code is here:
```C#
private void InitializeComponent()
        {
            this.dg = new System.Windows.Forms.DataGridView();
            this.Name2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            ((System.ComponentModel.ISupportInitialize)(this.dg)).BeginInit();
            this.SuspendLayout();
            // 
            // dg
            // 
            this.dg.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dg.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Name2});
            this.dg.Location = new System.Drawing.Point(60, 30);
            this.dg.Name = "dg";
            this.dg.RowHeadersWidth = 51;
            this.dg.RowTemplate.Height = 27;
            this.dg.Size = new System.Drawing.Size(573, 308);
            this.dg.TabIndex = 0;
            // 
            // Name2
            // 
            this.Name2.DataPropertyName = "TestName";
            this.Name2.HeaderText = "Col1";
            this.Name2.MinimumWidth = 6;
            this.Name2.Name = "Name2";
            this.Name2.Width = 125;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.dg);
            this.Name = "Form1";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dg)).EndInit();
            this.ResumeLayout(false);

        }
```

**Comment by mkaring** [comment] 2019-06-01 08:23
The warning points to a problem identifying the referenced property name. In this case it's looking for a property called `"TestName"`, but it's unable to find it.
Could you please add the code, how this property is defined? This is required to identify the source of the issue.

**Comment by ismlsmile** [comment] 2019-06-01 08:43
TestClass.cs:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TestWinForm
{
    class TestClass
    {
        public string TestName { get; set; }
    }
}


Form1.cs:

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace TestWinForm
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            List<TestClass> ar = new List<TestClass>();
            TestClass cls = new TestClass();
            cls.TestName = "aa";
            ar.Add(cls);

            dg.DataSource = ar;
        }
    }
}

**Comment by mkaring** [comment] 2019-06-01 10:43
I'm able to reproduce the error. It will be fixed in the next minor version. As a workaround I suggest marking the referenced property to exclude it from renaming using the `<Obfuscation>` attribute.

**Comment by mkaring** [comment] 2019-06-01 14:48
The new build of the master branch that can be downloaded from [the buildserver][1] contains a fix for this specific issue.

[1]: https://ci.appveyor.com/project/mkaring/confuserex/branch/master/artifacts

**Comment by ismlsmile** [comment] 2019-06-02 10:33
Thanks for your greak job.

**Comment by ismlsmile** [comment] 2019-06-02 10:34
Thanks for your great job!

**Comment by ismlsmile** [comment] 2019-06-02 10:42
I test the new version, there is no warning now, but when click the target file, no window is shown.

**Comment by mkaring** [comment] 2019-06-02 12:05
That points to a different issue. Can you provide a minimal working example (the solution for Visual Studio) that causes the issue so I can analyse it?

**Comment by ismlsmile** [comment] 2019-06-02 13:20
[TestWinForm.zip](https://github.com/mkaring/ConfuserEx/files/3244845/TestWinForm.zip)
 Here is the project code and the debug info, thank you:

 [INFO] Confuser.Core 1.3.0-alpha.6+48a74095c3 Copyright © 2014 Ki, 2018 Martin Karing
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'TestWinForm.exe'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
[DEBUG] WinForms found, enabling compatibility.
 [INFO] Processing module 'TestWinForm.exe'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'TestWinForm.exe'...
[DEBUG] Encrypting resources...
 [INFO] Finalizing...
[DEBUG] Saving to 'D:\Code\TestWinForm\TestWinForm\TestWinForm.exe'...
[DEBUG] Executing 'Export symbol map' phase...
 [INFO] Done.
Finished at 21:17, 0:02 elapsed.

**Comment by mkaring** [comment] 2019-06-02 19:28
Could you please also add your `*.crproj` file so I know the protections you have enabled?

**Comment by ismlsmile** [comment] 2019-06-03 01:49
[TestWinForm_crproj.zip](https://github.com/mkaring/ConfuserEx/files/3245553/TestWinForm_crproj.zip)

**Comment by kirsan31** [comment] 2019-07-24 21:09
/cc @mkaring 
Are you still with us? More then 1 month no updates to the project... :(

**Comment by mkaring** [comment] 2019-07-25 20:19
@kirsan31 Still around. Just very busy with the work I'm paid for.

**Comment by KvanTTT** [comment] 2019-07-28 15:15
Maybe it makes sense to add sponsor support for this repository?

**Comment by mkaring** [comment] 2019-09-07 18:32
@ismlsmile Sorry that it took so long. I finally managed to fix all the issues with your test application. The issues were mostly related to the fact that those applications were compiled with .NET Framework 2.0 as target framework. The problem is that the runtime code that is deployed with ConfuserEx 1.x, is always compiled for .NET Framework 4.6.1. This results in incompatible code from for some protections.
The issues in detail were related to the constants and the anti debug protection. Both of those issues are fixed.

You can find the download to the version of ConfuserEx that contains the fixes here: [ConfuserEx 221 - AppVeyor][0].

In general I would suggest using the ConfuserEx 2.x versions for projects targeting anything but the .NET Framework 4.x, because this newer version handles the runtime code it injects a lot differently. It uses dedicated versions for different versions of the .NET Framwork.

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/27254164/artifacts

**Comment by mkaring** [comment] 2019-09-07 20:48
If your project yields any further problems, please report them in a new issue!

**Closed by mkaring** 2019-09-07 20:48 UTC
Labels: bug
