### ISSUE TITLE
Generic class sometimes missing generic arguments in name after rename protection

### ISSUE THREAD

**Issue by dmirmilshteyn** [mkaring/ConfuserEx#37] opened 2019-04-06 00:22 UTC
I've got a case where a generic type does not have its generic arguments applied to the name - instead, the name is obfuscated and the generic arguments are trimmed off (`A'1 -> _ujkljsfuoiu` instead of the expected `A'1 -> _ujkljsfuoiu'1`. It seems to happen with the following setup:

1) Enable decodable renaming
2) Create a non-generic class, A
3) Create a generic class, A`1
4) Apply renaming protection

The problem only appears when the non-generic class A is loaded/obfuscated before the generic variant. If the generic class is processed first, it is named correctly.

As a result, attempting to run the program/load an assembly like this fails with a duplicate type exception similar to the following:

`Unhandled Exception: System.BadImageFormatException: Duplicate type with name '_KXAnX9u6N2HxWpPt3OaOUtHSGLF' in assembly 'ConfuserTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

Confuser version: 2.0-master
Minimal example: [ConfuserTest.zip](https://github.com/mkaring/ConfuserEx/files/3049990/ConfuserTest.zip)

Thanks!

**Comment by mkaring** [comment] 2019-04-06 14:45
Good find. The issue tracks back to the 1.x branch.
It will be fixed in 1.2 and 2.0.

**Comment by mkaring** [comment] 2019-04-06 15:16
The issue is fixed in `master` and `release/2.0`.
I'll keep the issue open until I also added a unit test for the issue. But you can use the current builds of both branches and have a working version.

**Comment by dmirmilshteyn** [comment] 2019-04-07 00:53
Great, thank you!

**Closed** 2019-05-27 18:27 UTC
Labels: bug
