### ISSUE TITLE
Runtime Binder Exception when using dynamic variable function in a function

### ISSUE THREAD

**Issue by NaveenBadal** [mkaring/ConfuserEx#349] opened 2021-05-13 03:34 UTC
I am having the issue , of Runtime under Exception, after obfuscating the DLL, where I have a dynamic variable in a function. 

- ConfuserEx Version: 1.5.0
- Target Framework: 4.6.1
- Operating System: Window 10

Steps to Reproduce:

1.
I have set the preset to "Maximum" and mostly all of the protections are enabled except one or two like reference proxy. 
One thing that I found out is, when I removed the rename protection, then after obfuscating it is working fine. But then it will not perform the rename protection in any of my DLL. Please suggest a way to do this. So that my dynamic variable will work after obfuscation , along with the rename protection.

**Comment by mkaring** [comment] 2021-05-13 09:10
This is very likely a duplicate of #345. The issue is known and I'm looking into resolving it. You can work around the issue by disabling the rename protection for the specific method you are calling with the dynamic parameter.

**Comment by mkaring** [comment] 2021-05-16 10:12
I've got a new version fixing this issue. You can download it [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/39182843/artifacts).

Please give it a try and tell me if it works for your project or not.

**Comment by NaveenBadal** [comment] 2021-05-16 10:52
Hello

I just tried this version in our project and it is working fine. Now we are able to use the dynamic variable in a function and can get the value with the rename protection. Thanks for your quick help.

**Closed** 2021-05-16 10:56 UTC
Labels: bug, duplicate
